stages:
  - build
  - test
  - deploy
  - cleanup

# Задача для сборки проекта, запускается только на1 основных ветках и для мерж-реквестов
build_job:
  stage: build
  script:
    - echo "Building the project..."
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always  # Всегда запускается для указанных веток или для мерж-реквестов

# Задача для тестирования, запускается только при изменении файлов в определенных директориях
test_job:
  stage: test
  script:
    - echo "Running tests..."
  rules:
    - changes:
        - "src/**/*"
        - "tests/**/*"  # Запускается при изменениях в директориях src/ или tests/

# Деплой на продакшн, только когда все тесты пройдены и установлен тег
deploy_prod:
  stage: deploy
  script:
    - echo "Deploying to production..."
  rules:
    - if: '$CI_COMMIT_TAG && $CI_PIPELINE_SOURCE == "push"'
      when: on_success  # Запуск только если предыдущие задачи успешно выполнены и это пуш с тегом

# Деплой на стейджинг, только когда коммит в ветке develop
deploy_staging:
  stage: deploy
  script:
    - echo "Deploying to staging..."
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always  # Всегда запускается для ветки develop

# Задача для очистки, которая выполняется после успешного деплоя
cleanup_job:
  stage: cleanup
  script:
    - echo "Performing cleanup..."
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# Специфическая задача, запускаемая по расписанию для выполнения бэкапов
scheduled_backup_job:
  stage: deploy
  script:
    - echo "Running scheduled backup..."
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always  # Запускается по расписанию, не зависит от других задач

# Задача для проверки безопасности, запускается для всех коммитов кроме тегов
security_scan:
  stage: test
  script:
    - echo "Performing security scan..."
  rules:
    - if: '$CI_COMMIT_REF_NAME != $CI_COMMIT_TAG'
      when: always  # Запускается для всех коммитов, кроме тех, что с тегами

# Создание артефактов только для определенных веток
artifact_creation:
  stage: build
  script:
    - mkdir build && cd build
    - echo "Creating artifacts..."
    - echo "Some binaries file" > bin
  artifacts:
    paths:
      - build/
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "release"'
      when: always
